package pe.edu.udaff.entities;
// Generated 25-may-2020 13:21:34 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "partner", catalog = "fastmarketbd")
public class Partner implements java.io.Serializable {

	private Integer idpartner;
	private String name;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Partner() {
	}

	public Partner(String name, Set<Producto> productos) {
		this.name = name;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpartner", unique = true, nullable = false)
	public Integer getIdpartner() {
		return this.idpartner;
	}

	public void setIdpartner(Integer idpartner) {
		this.idpartner = idpartner;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
