package pe.edu.udaff.entities;
// Generated 04-nov-2020 10:46:38 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "fastmarketbd")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private Categoria categoria;
	private Marca marca;
	private Partner partner;
	private String nombre;
	private BigDecimal precio;
	private int cantidad;
	private String descripcion;
	private String urlimagen;
	private byte caracteristicas;
	private Byte feature;
	private Boolean activo;

	public Producto() {
	}

	public Producto(Categoria categoria, Marca marca, Partner partner, String nombre, BigDecimal precio, int cantidad,
			byte caracteristicas) {
		this.categoria = categoria;
		this.marca = marca;
		this.partner = partner;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.caracteristicas = caracteristicas;
	}

	public Producto(Categoria categoria, Marca marca, Partner partner, String nombre, BigDecimal precio, int cantidad,
			String descripcion, String urlimagen, byte caracteristicas, Byte feature, Boolean activo) {
		this.categoria = categoria;
		this.marca = marca;
		this.partner = partner;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.urlimagen = urlimagen;
		this.caracteristicas = caracteristicas;
		this.feature = feature;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpartner", nullable = false)
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@Column(name = "nombre", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false, precision = 18)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "urlimagen", length = 100)
	public String getUrlimagen() {
		return this.urlimagen;
	}

	public void setUrlimagen(String urlimagen) {
		this.urlimagen = urlimagen;
	}

	@Column(name = "caracteristicas", nullable = false)
	public byte getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(byte caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	@Column(name = "feature")
	public Byte getFeature() {
		return this.feature;
	}

	public void setFeature(Byte feature) {
		this.feature = feature;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
